# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello.proto for package 'hello'

require 'grpc'
require_relative 'hello_pb'

module Hello
  module Greeter
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'hello.Greeter'

      rpc :HelloRequestResponse, ::Hello::Request, ::Hello::Response
      rpc :HelloServerStreamer, ::Hello::Request, stream(::Hello::Response)
      rpc :HelloClientStreamer, stream(::Hello::Request), ::Hello::Response
      rpc :HelloBidiStreamer, stream(::Hello::Request), stream(::Hello::Response)
    end

    Stub = Service.rpc_stub_class
  end
end
