# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'


descriptor_data = "\n\x0bhello.proto\x12\x05hello\"\x16\n\x07Request\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x17\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xf8\x01\n\x07Greeter\x12\x39\n\x14HelloRequestResponse\x12\x0e.hello.Request\x1a\x0f.hello.Response\"\x00\x12:\n\x13HelloServerStreamer\x12\x0e.hello.Request\x1a\x0f.hello.Response\"\x00\x30\x01\x12:\n\x13HelloClientStreamer\x12\x0e.hello.Request\x1a\x0f.hello.Response\"\x00(\x01\x12:\n\x11HelloBidiStreamer\x12\x0e.hello.Request\x1a\x0f.hello.Response\"\x00(\x01\x30\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hello
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.Response").msgclass
end
