# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello2.proto

require 'google/protobuf'


descriptor_data = "\n\x0chello2.proto\x12\x06hello2\"\x16\n\x07Request\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x17\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x80\x02\n\x07Greeter\x12;\n\x14HelloRequestResponse\x12\x0f.hello2.Request\x1a\x10.hello2.Response\"\x00\x12<\n\x13HelloServerStreamer\x12\x0f.hello2.Request\x1a\x10.hello2.Response\"\x00\x30\x01\x12<\n\x13HelloClientStreamer\x12\x0f.hello2.Request\x1a\x10.hello2.Response\"\x00(\x01\x12<\n\x11HelloBidiStreamer\x12\x0f.hello2.Request\x1a\x10.hello2.Response\"\x00(\x01\x30\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hello2
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello2.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello2.Response").msgclass
end
